# For toggle-pane.yazi
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "q" ]
run  = "close"
desc = "Close the current tab, or quit if it's the last"

[[mgr.prepend_keymap]]
on   = [ "<C-c>" ]
run  = "quit"
desc = "Quit the process"

[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "arrow 1"
desc = "Down without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "arrow -1"
desc = "Up without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "<Space>" ]
run  = "cd --interactive"
desc = "Goto file"
