### toggle-pane.yazi

[[mgr.prepend_keymap]]
on   = "="
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"


### zoom.yazi

# [[mgr.prepend_keymap]]
# on   = "+"
# run  = "plugin zoom 1"
# desc = "Zoom in hovered file"
#
# [[mgr.prepend_keymap]]
# on   = "-"
# run  = "plugin zoom -1"
# desc = "Zoom out hovered file"




[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = [ "T" ]
run  = "tab_create"
desc = "Create tab at default directory"

[[mgr.prepend_keymap]]
on   = [ "q" ]
run  = "close"
desc = "Close the current tab, or quit if it's the last"

[[mgr.prepend_keymap]]
on   = [ "<C-c>" ]
run  = "quit"
desc = "Quit the process"

[[mgr.prepend_keymap]]
on   = [ "j" ]
run  = "arrow 1"
desc = "Down without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "k" ]
run  = "arrow -1"
desc = "Up without wrap-around"

[[mgr.prepend_keymap]]
on   = [ "<Space>" ]
run  = "cd --interactive"
desc = "Goto file"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd sftp://uaptt"
desc = "Connect to uaptt"
